/*
 * File automatically generated by
 * gengen 1.4 by Lorenzo Bettini 
 * http://www.gnu.org/software/gengen
 */

#ifndef MEMBERS_GEN_GEN_CLASS_H
#define MEMBERS_GEN_GEN_CLASS_H

#include <string>
#include <iostream>

using std::string;
using std::ostream;

class members_gen_gen_class
{
 protected:
  string member_name;
  string member_type;

 public:
  members_gen_gen_class()
  {
  }
  
  members_gen_gen_class(const string &_member_name, const string &_member_type) :
    member_name (_member_name), member_type (_member_type)
  {
  }

  void set_member_name(const string &_member_name)
  {
    member_name = _member_name;
  }

  void set_member_type(const string &_member_type)
  {
    member_type = _member_type;
  }

  void generate_members_gen(ostream &stream, unsigned int indent = 0)
  {
    string indent_str (indent, ' ');
    indent = 0;
  
    stream << member_type;
    stream << " ";
    stream << member_name;
    stream << ";";
    stream << "\n";
    stream << indent_str;
  }
};

#endif // MEMBERS_GEN_GEN_CLASS_H
